### PR TITLE
Return exceptions

### PR DESCRIPTION
**Pull request by boryn**

### CODE REVIEW

**Comment by Kovah** [comment]
I have tested this locally and works as expected. I think this could be merged once the two small styling issues are fixed.

**Comment by atymic** [comment]
@boryn can you fix those  please?

**Comment by boryn** [comment]
> @boryn can you fix those please?

Just for confirmation - do you refer to this:
https://github.styleci.io/analyses/Ko2VOA ?

These are lines not touched by me, but of course I can fix them.

**Comment by Kovah** [comment]
Weird that they popped up in your pull request, but thank you for taking care of this. Will merge it and include it in the next version. 👍

**Comment by boryn** [comment]
I'm happy the library is live again! :)

**Comment by boryn** [comment]
Hi!

Would you make a new release including this merge?

Thank you :)

**Comment by atymic** [comment]
@Kovah can you release :)

**Comment by Kovah** [comment]
Will do so as soon as I have time.

**Pull request merged**
